### PR TITLE
Fix Point Clouds Getting Culled Prematurely

### LINKED ISSUE #4831: Point cloud disappears in scene in zooming
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When a cloud is added to scene in arcball mode, and zoom it by mouse wheel, sometimes it will disapper

I found this issue in my application:

https://user-images.githubusercontent.com/18083216/156388854-54c5d038-cd7c-4959-b213-c09d36a39aea.mp4

and I tried it in latest master by Open3D:

https://user-images.githubusercontent.com/18083216/156388978-2cb81646-40cb-48e6-90dd-01c69a03ccab.mp4

it looks like a camera transforming issue

this is the file I'm using:
[7.zip](https://github.com/isl-org/Open3D/files/8170558/7.zip)

### Steps to reproduce the bug

```python
using latest Open3D:
 7.ply

rotate to some angles showed in my video, try zooming out and in to reproduce this issue
```

### Error message

None

### Expected behavior

Cloud could be small in view, even as a point, but should not disapper

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.9
- Open3D version: 0.15.1
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 9.3
```

### Additional information

None

### PR DESCRIPTION
**Pull request by errissa**
Fixes #4831 Can be tested using the the model provided by issue author.

Computation of dynamic far plane implicitly assumed the point cloud is near the origin. If it is sufficiently far from the origin then the point cloud get prematurely/unexpectedly culled out at certain view angles.

---
This change is [Reviewable](https://reviewable.io/reviews/isl-org/open3d/4842)

### CODE REVIEW

File: cpp/open3d/visualization/rendering/Camera.cpp [hunk 1]
```diff
@@ -74,10 +74,12 @@ float Camera::CalcFarPlane(
...
     auto far1 = scene_bounds.GetMinBound().norm();
     auto far2 = scene_bounds.GetMaxBound().norm();
-    auto far3 = camera.GetModelMatrix().translation().cast<double>().norm();
+    auto cam_xlate = camera.GetModelMatrix().translation().cast<double>();
+    auto far3 = cam_xlate.norm();
+    auto far4 = (scene_bounds.GetCenter() - cam_xlate).norm();
     auto model_size = 2.0 * scene_bounds.GetExtent().norm();
     auto far = std::max(MIN_FAR_PLANE,
-                        std::max(std::max(far1, far2), far3) + model_size);
+                        std::max({far1, far2, far3, far4}) + model_size);
```
Comment (ssheorey) [inline cpp/open3d/visualization/rendering/Camera.cpp:82]: I can still make the point cloud disappear pre-maturely with some effort (zooming out and translating and rotating far enough). 

https://user-images.githubusercontent.com/41028320/156813254-09a04386-b0ef-44ee-92d0-4671a37fefc7.mov

Should we instead have 
```c++
auto far1 = (scene_bounds.GetMinBound() - cam_xlate).norm();
auto far2 = (scene_bounds.GetMaxBound() - cam_xlate).norm();
auto far3 = cam_xlate.norm();
auto far = std::max(MIN_FAR_PLANE,
                        std::max({far1, far2, far3}) + model_size);
```

**Review by ssheorey — CHANGES_REQUESTED** [review]

File: cpp/open3d/visualization/rendering/Camera.cpp (hunk 1 above)
Comment (forrestjgq) [reply cpp/open3d/visualization/rendering/Camera.cpp:82]: I've tried, this fixes my issue.

**Review by ssheorey — APPROVED** [review]
Looks good.
