### PR TITLE
Fixes and improvements for point selection in O3DVisualizer (fixes #6725)

### LINKED ISSUE #6725: O3DVisualizer: Make size of selection indicator points adjustable, choose smarter default and make points removable
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Proposed new feature or change

In the O3DVisualizer the current selection indicators points are massive if you load a point cloud which is scaled in e.g. mm:
selection_point_size

In the "old" VisualizerWithEditing it looks fine, but I cannot use it as it crashes when trying to run it in a non-blocking way (see https://github.com/isl-org/Open3D/issues/4378):
old_visu

Smaller points are essential for robustly performing a manual N-point registration by point picking. So a UI element and API to adjust the point size would be appreciated. Also a smart default (like in the old visualizer would be nice.

Further it would be helpful to remove points after the fact (again, like in the old visualizer).

### References

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by danrauch**
Fixes and improvements:
- make points removable by correctly forwarding the key modifier to the already implemented function
- fix bounding box calculation for picked point size selection (manual bbox extend calculation was wrong)
- fix crash occurring when trying to make selection and non-pickable geometries where in scene

## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6725 
-   [ ] New feature (non-breaking change which adds functionality). 
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Motivation and Context

See issue

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.

## Description

See issue

### CODE REVIEW

File: cpp/open3d/visualization/visualizer/O3DVisualizer.cpp [hunk 1]
```diff
@@ -488,11 +490,14 @@ struct O3DVisualizer::Impl {
         });
 
 #if __APPLE__
-        const char *selection_help =
-                "Cmd-click to select a point\nCmd-ctrl-click to polygon select";
+        const char *selection_help = const char *selection_help =
```
Comment (errissa) [inline cpp/open3d/visualization/visualizer/O3DVisualizer.cpp:493]: This causes compilation error on MacOS

**Review by errissa — CHANGES_REQUESTED** [review]
Looks good other than the MacOS issue. Please resolve the CI failures and feel free to let me know if you need any help with it. Thank you for your contribution!

File: cpp/open3d/visualization/visualizer/O3DVisualizer.cpp (hunk 1 above)
Comment (danrauch) [reply cpp/open3d/visualization/visualizer/O3DVisualizer.cpp]: Fixed in c4d26f0

**Comment by ssheorey** [comment]
Good to merge once CI passes. Thanks @danrauch for this useful bugfix.

**Review by ssheorey — APPROVED** [review]
