### PR TITLE
fix X11 access on wayland

### LINKED ISSUE #7162: Failed creating OpenGL window.
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

I am trying to visualise a geometry on an Ubuntu 24.04 desktop via `draw_geometries` but the program crashes with `Failed creating OpenGL window.`.

Similar issues on other configurations:
- https://github.com/isl-org/Open3D/issues/5126
- https://github.com/isl-org/Open3D/issues/6072

### Steps to reproduce the bug

```python
import open3d as o3d
o3d.visualization.draw_geometries([o3d.geometry.TriangleMesh.create_coordinate_frame()])
```

### Error message

```
[Open3D WARNING] GLFW Error: Wayland: The platform does not support setting the window position
[Open3D WARNING] Failed to initialize GLEW.
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.
```

### Expected behavior

A window should be shown.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 24.04
- Python version: ´3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0]´
- Open3D version: ´0.19.0´
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

I am using the "Intel Arc Graphics" GPU on Wayland (Ubuntu 24.04 default).

`inxi -G`:
```
Graphics:
  Device-1: Intel Meteor Lake-P [Intel Arc Graphics] driver: i915 v: kernel
  Device-2: Luxvisions Innotech Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell v: 46.0 driver: dri: iris gpu: i915
    resolution: 3072x1728~60Hz
  API: EGL v: 1.5 drivers: iris,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel v: N/A renderer: Mesa
    Intel Arc Graphics (MTL)
```

### PR DESCRIPTION
**Pull request by christian-rauch**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #7162
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

On Wayland, Open3D still calls X11 specific functions and dereferences NULL pointers. See #7162. This PR fixes this by checking the platform (X11 / Wayland) via `glfwGetPlatform()` and avoid using X11 specific functions.

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

### CODE REVIEW

File: cpp/open3d/visualization/gui/NativeLinux.cpp [hunk 1]
```diff
@@ -18,20 +19,31 @@ namespace visualization {
...
-    XSendEvent(d, x11win, False, ExposureMask, &e);
-    XFlush(d);
+        XEvent e;
+        memset(&e, 0, sizeof(e));
+        e.type = Expose;
+        e.xexpose.window = x11win;
+
+        XSendEvent(d, x11win, False, ExposureMask, &e);
+        XFlush(d);
+    }
```
Comment (ssheorey) [inline cpp/open3d/visualization/gui/NativeLinux.cpp:46]: Is there a corresponding action needed in Wayland? I understand this is telling X11 to redraw the window.

**Review by ssheorey — COMMENTED** [review]
Thanks @christian-rauch better wayland support is great! Have you tested with this PR in wayland? Can you build the examples (`examples/cpp` folder), run them (typically no arguments needed) and confirm that they work properly:

- Visualizer.cpp
- LineSet.cpp
- PointCLoud.cpp
- TriangleMesh.cpp
- Octree.cpp
- Voxelization.cpp

This needs manual checking since we don't have CI for visualization.

**Comment by christian-rauch** [comment]
Yes, I tested this on Wayland. The crashes on Wayland were the reason I opened this PR.

These examples work on Wayland:
- `./ViewGeometry [file]`
- `./examples/LineSet [file]`
- `./examples/Visualizer mesh [file]`
- `./examples/TriangleMesh sphere`
- `./examples/Octree [file]`

I could not test the other executables as I don't have a point cloud at hand.

But there are some examples, such as `./Draw`, that run (do not crash) with the following message on the terminal:
```
[error] GLFW error: Wayland: The platform does not support setting the window position
```
and don't show a window. This message is not shown for the working examples above.

File: cpp/open3d/visualization/gui/NativeLinux.cpp (hunk 1 above)
Comment (christian-rauch) [reply cpp/open3d/visualization/gui/NativeLinux.cpp:46]: I don't know why this is done manually here and not via GLFW. I would naively assume that this is not required here and that the X11 support would work without it.

In any case, there is no such thing as an `Expose` event on Wayland.

Comment (christian-rauch) [reply cpp/open3d/visualization/gui/NativeLinux.cpp:46]: I just removed the code in `PostNativeExposeEvent` and ran `ViewGeometry` on `Xwayland` without issues. So I guess this is redundant.

Comment (ssheorey) [reply cpp/open3d/visualization/gui/NativeLinux.cpp:46]: I'm not sure that this code is called by `DrawGeometries`. We have two visualizers in Open3D - the legacy / pure OpenGL one (`DrawGeometries`) and the new filament + GUI visualizer (the code in the gui and rendering folders) - this is called by `draw()` and `O3DVisualizer`.

**Comment by ssheorey** [comment]
> Yes, I tested this on Wayland. The crashes on Wayland were the reason I opened this PR.
> 
> These examples work on Wayland:
> 
>     * `./ViewGeometry [file]`
> 
>     * `./examples/LineSet [file]`
> 
>     * `./examples/Visualizer mesh [file]`
> 
>     * `./examples/TriangleMesh sphere`
> 
>     * `./examples/Octree [file]`
> 
> 
> I could not test the other executables as I don't have a point cloud at hand.
> 
> But there are some examples, such as `./Draw`, that run (do not crash) with the following message on the terminal:
> 
> ```
> [error] GLFW error: Wayland: The platform does not support setting the window position
> ```
> 
> and don't show a window. This message is not shown for the working examples above.

As mentioned in my earlier comment, there are 2 visualizers in Open3D. It looks like this PR updates only the legacy visualizer to work with wayland. We need another update somewhere for the new filament based visualizer to work.

If you'd like to look at `draw()` on wayland as well, I'd appreciate it. In any case, thanks for this debugging and PR. I've approved this PR and will merge it next week. Let me know if there are any updates that you'd like before then.

PS: Don't worry about the CI failures - they are unrelated and due to cmake being upgrade to 4 (etc.). Most of them should be fixed in main.

**Review by ssheorey — APPROVED** [review]

File: cpp/open3d/visualization/gui/NativeLinux.cpp (hunk 1 above)
Comment (christian-rauch) [reply cpp/open3d/visualization/gui/NativeLinux.cpp:46]: I didn't know that there are two different visualiser implementations. That explains why the GUI examples behave differently.

**Comment by christian-rauch** [comment]
> If you'd like to look at `draw()` on wayland as well, I'd appreciate it. In any case, thanks for this debugging and PR. I've approved this PR and will merge it next week. Let me know if there are any updates that you'd like before then.

At the moment, I am only visualising point clouds and meshes. I may look into the new GUI implementation later. Maybe this is just an issue with how GLFW is used. But for now, I would appreciate it if the fixes could be merged, so I do not have to manage multiple custom branches.
