### PR TITLE
Add macOS arm64 CI runner, fix macOS arm64 builds

### LINKED ISSUE #6147: Cannot compile filament from the source on macOS 13.3.1 (M1 macOS)
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on macOS 13.3.1) with:

```
mkdir build
cd build
cmake ..
make -j$(sysctl -n hw.physicalcpu)
```

### Execute cmake

```
cmake ..
-- Setting build type to Release as none was specified.
-- CMAKE_BUILD_TYPE is set to Release.
-- ccache found at /opt/homebrew/bin/ccache
-- Downloading third-party dependencies to /Users/user/OpenProjects/open3d/Open3D/3rdparty_downloads
CMake Deprecation Warning at CMakeLists.txt:189 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Open3D 0.17.0+a5be78cfe
-- Found Python3: /Users/user/.pyenv/shims/python3.9 (found suitable version "3.9.15", minimum required is "3.6") found components: Interpreter Development Development.Module Development.Embed
-- Performing Test FLAG_fstack_protector
-- Performing Test FLAG_fstack_protector - Success
-- Performing Test FLAG_Wformat
-- Performing Test FLAG_Wformat - Success
-- Performing Test FLAG_Wformat_security
-- Performing Test FLAG_Wformat_security - Success
-- Performing Test FLAGLINKER__dead_strip
-- Performing Test FLAGLINKER__dead_strip - Success
-- Performing Test FLAG____CONFIG_Release__LINKER__S__x_
-- Performing Test FLAG____CONFIG_Release__LINKER__S__x_ - Success
-- Using security hardening compiler flags: $<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=-fstack-protector,-Wformat,-Wformat-security>;$<$<COMPILE_LANGUAGE:CXX>:-fstack-protector;-Wformat;-Wformat-security>
-- Using security hardening linker flags: $<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=LINKER:-dead_strip,$<$<CONFIG:Release>:LINKER:-S,-x>>;$<$<COMPILE_LANGUAGE:CXX>:LINKER:-dead_strip;$<$<CONFIG:Release>:LINKER:-S,-x>>
-- Using security hardening compiler definitions: _FORTIFY_SOURCE=2
-- Performing Test FLAG_load_hidden
-- Performing Test FLAG_load_hidden - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Using installed third-party library 3rdparty_threads
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- Unable to find installed third-party library 3rdparty_openmp
-- Building library 3rdparty_glfw from source
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
-- Using Cocoa for window creation
-- Building third-party library JPEG from source
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - NOTFOUND
-- NASM assembler not found - libjpeg-turbo performance may suffer
-- libturbojpeg: WITH_CRT_DLL=OFF
-- pybind11 v2.6.2
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Building third-party library Filament from source
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework
-- Using installed third-party library 3rdparty_opengl
-- Building OpenBLAS with LAPACK from source
-- gfortran found at
-- OPENBLAS_INCLUDE_DIR: /Users/user/OpenProjects/open3d/Open3D/build/openblas/include/openblas/
-- OPENBLAS_LIB_DIR /Users/user/OpenProjects/open3d/Open3D/build/openblas/lib
-- OPENBLAS_LIBRARIES: openblas
CMake Warning at 3rdparty/find_dependencies.cmake:1672 (message):
  All link warnings have been disabled on Apple Silicon builds due to the
  large number of spurious warnings that are generated.  If you need to see
  link warnings please build with -DCMAKE_BUILD_TYPE=Debug.
Call Stack (most recent call first):
  CMakeLists.txt:496 (include)


CMake Warning at 3rdparty/find_dependencies.cmake:1809 (message):
  IPP-ICV disabled: Unsupported Platform.
Call Stack (most recent call first):
  CMakeLists.txt:496 (include)


-- open3d_sycl_target_sources(core): PRIVATE
-- PYPI_PACKAGE_NAME: open3d
-- ================================================================================
-- Open3D 0.17.0 Configuration Summary
-- ================================================================================
-- Enabled Features:
--   OpenMP .................................. OFF
--   Headless Rendering ...................... OFF
--   Azure Kinect Support .................... OFF
--   Intel RealSense Support ................. OFF
--   CUDA Support ............................ OFF
--   SYCL Support ............................ OFF
--   ISPC Support ............................ OFF
--   Build GUI ............................... ON
--   Build WebRTC visualizer ................. OFF
--   Build Shared Library .................... OFF
--   Build Unit Tests ........................ OFF
--   Build Examples .......................... ON
--   Build Python Module ..................... ON
--   Build Jupyter Extension ................. OFF
--   Build TensorFlow Ops .................... OFF
--   Build PyTorch Ops ....................... OFF
--   Build Benchmarks ........................ OFF
--   Bundle Open3D-ML ........................ OFF
--   Force GLIBCXX_USE_CXX11_ABI= ............ 0
-- ================================================================================
-- Third-Party Dependencies:
--   Assimp .................................. yes (build from source)
--   BLAS .................................... yes (build from source)
--   curl .................................... yes (build from source)
--   Eigen3 .................................. yes (build from source)
--   filament ................................ yes (build from source)
--   fmt ..................................... yes (build from source)
--   GLEW .................................... yes (build from source)
--   GLFW .................................... yes (build from source)
--   googletest .............................. no
--   imgui ................................... yes (build from source)
--   ippicv .................................. no
--   JPEG .................................... yes (build from source)
--   jsoncpp ................................. yes (build from source)
--   liblzf .................................. yes (build from source)
--   msgpack ................................. yes (build from source)
--   nanoflann ............................... yes (build from source)
--   OpenGL .................................. yes
--   PNG ..................................... yes (build from source)
--   qhullcpp ................................ yes (build from source)
--   librealsense ............................ no
--   TBB ..................................... yes (build from source)
--   tinyfiledialogs ......................... yes (build from source)
--   TinyGLTF ................................ yes (build from source)
--   tinyobjloader ........................... yes (build from source)
--   VTK ..................................... yes (build from source)
--   WebRTC .................................. no
--   ZeroMQ .................................. yes (build from source)
-- ================================================================================
-- Configuring done (9.6s)
-- Generating done (0.3s)
-- Build files have been written to: /Users/user/OpenProjects/open3d/Open3D/build
```

### First error (fixed)

I got the following error, at the first.

```
1 error generated.
make[5]: *** [third_party/spirv-tools/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/basic_block.cpp.o] Error 1
In file included from /Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/opt/aggressive_dead_code_elim_pass.cpp:18:
In file included from /Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/opt/aggressive_dead_code_elim_pass.h:30:
In file included from /Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/opt/basic_block.h:30:
In file included from /Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/opt/instruction_list.h:28:
/Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/util/ilist.h:341:7: error: variable 'sentinel_count' set but not used [-Werror,-Wunused-but-set-variable]
  int sentinel_count = 0;
```

I fixed this error for adding `(void)sentinel_count;` like the below.

```C
void IntrusiveList<NodeType>::Check(NodeType* start) {
  int sentinel_count = 0;
  NodeType* p = start;
  do {
    assert(p != nullptr);
    assert(p->next_node_->previous_node_ == p);
    assert(p->previous_node_->next_node_ == p);
    if (p->is_sentinel_) sentinel_count++;
    p = p->next_node_;
  } while (p != start);
  assert(sentinel_count == 1 && "List should have exactly 1 sentinel node.");
  (void)sentinel_count;
```

### Error message

```shell
In file included from /Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/opt/merge_return_pass.cpp:15:
/Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/opt/merge_return_pass.h:121:5: error: definition of implicit copy assignment operator for 'StructuredControlState' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
    StructuredControlState(const StructuredControlState&) = default;
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/move.h:34:15: note: in implicit copy assignment operator for 'spvtools::opt::MergeReturnPass::StructuredControlState' first required here
    *__result = _IterOps<_AlgPolicy>::__iter_move(__first);
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/move.h:54:17: note: in instantiation of function template specialization 'std::__move_impl<std::_ClassicAlgPolicy, spvtools::opt::MergeReturnPass::StructuredControlState *, spvtools::opt::MergeReturnPass::StructuredControlState *, spvtools::opt::MergeReturnPass::StructuredControlState *>' requested here
    return std::__move_impl<_AlgPolicy, _InType*, _InType*, _OutType*>(__first, __last, __result);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/move.h:87:8: note: in instantiation of function template specialization 'std::__move_impl<std::_ClassicAlgPolicy, spvtools::opt::MergeReturnPass::StructuredControlState, spvtools::opt::MergeReturnPass::StructuredControlState, void>' requested here
  std::__move_impl<_AlgPolicy>(__last_base, __first_base, __result_first);
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/move.h:97:21: note: in instantiation of function template specialization 'std::__move_impl<std::_ClassicAlgPolicy, spvtools::opt::MergeReturnPass::StructuredControlState *, spvtools::opt::MergeReturnPass::StructuredControlState *, 0>' requested here
  auto __ret = std::__move_impl<_AlgPolicy>(
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/move.h:114:15: note: in instantiation of function template specialization 'std::__move<std::_ClassicAlgPolicy, std::reverse_iterator<spvtools::opt::MergeReturnPass::StructuredControlState *>, std::reverse_iterator<spvtools::opt::MergeReturnPass::StructuredControlState *>, std::reverse_iterator<spvtools::opt::MergeReturnPass::StructuredControlState *>>' requested here
  return std::__move<_ClassicAlgPolicy>(__first, __last, __result).second;
              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__memory/uninitialized_algorithms.h:635:17: note: in instantiation of function template specialization 'std::move<std::reverse_iterator<spvtools::opt::MergeReturnPass::StructuredControlState *>, std::reverse_iterator<spvtools::opt::MergeReturnPass::StructuredControlState *>>' requested here
    return std::move(__first1, __last1, __first2);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/vector:914:27: note: in instantiation of function template specialization 'std::__uninitialized_allocator_move_if_noexcept<std::allocator<spvtools::opt::MergeReturnPass::StructuredControlState>, std::reverse_iterator<spvtools::opt::MergeReturnPass::StructuredControlState *>, std::reverse_iterator<spvtools::opt::MergeReturnPass::StructuredControlState *>, spvtools::opt::MergeReturnPass::StructuredControlState, void>' requested here
    __v.__begin_   = std::__uninitialized_allocator_move_if_noexcept(
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/vector:1581:5: note: in instantiation of member function 'std::vector<spvtools::opt::MergeReturnPass::StructuredControlState>::__swap_out_circular_buffer' requested here
    __swap_out_circular_buffer(__v);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/vector:1600:9: note: in instantiation of function template specialization 'std::vector<spvtools::opt::MergeReturnPass::StructuredControlState>::__emplace_back_slow_path<spvtools::opt::Instruction *&, spvtools::opt::Instruction *&>' requested here
        __emplace_back_slow_path(_VSTD::forward<_Args>(__args)...);
        ^
/Users/user/OpenProjects/open3d/Open3D/build/filament/src/ext_filament/third_party/spirv-tools/source/opt/merge_return_pass.cpp:79:14: note: in instantiation of function template specialization 'std::vector<spvtools::opt::MergeReturnPass::StructuredControlState>::emplace_back<spvtools::opt::Instruction *&, spvtools::opt::Instruction *&>' requested here
      state_.emplace_back(mergeInst, mergeInst);
             ^
1 error generated.
make[5]: *** [third_party/spirv-tools/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/merge_return_pass.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [third_party/spirv-tools/source/opt/CMakeFiles/SPIRV-Tools-opt.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [filament/src/ext_filament-stamp/ext_filament-build] Error 2
make[1]: *** [CMakeFiles/ext_filament.dir/all] Error 2
make: *** [all] Error 2
```

### Open3D, Python and System information

```markdown
- Operating system: macOS 13.3.1 (M1/Arm64)
- Python version: 3.8.10 (default, Jul 14 2021, 22:33:06)
- Open3D version: a5be78cfe3da627ce6a38a7905e3e5cd6a64d811
- System architecture: apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

### Additional information

It seems the `filament` is old. Is it possible to use the latest versions?

Best regards.

### LINKED ISSUE #6336: Open3d-devel support for macOS arm64 Apple Silicon, please
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Proposed new feature or change

self-explanatory, please see issue title

### References

https://github.com/isl-org/Open3D/issues/6334#issuecomment-1695235532

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sitic**
GitHub macOS arm64 runners are now in [public beta](https://github.com/actions/runner-images/tree/main). Add them for testing and to build wheels.

## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6147
-   [x] New feature (non-breaking change which adds functionality). Resolves #6336
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

### CODE REVIEW

File: util/ci_utils.sh [hunk 1]
```diff
@@ -140,7 +146,7 @@ build_pip_package() {
     echo "Building Open3D wheel"
     options="$(echo "$@" | tr ' ' '|')"
 
-    BUILD_FILAMENT_FROM_SOURCE=OFF
+    BUILD_FILAMENT_FROM_SOURCE=ON
```
Comment (ssheorey) [inline util/ci_utils.sh:149]: This only needs to be built once (or when the filament version changes), so we should keep `BUILD_FILAMENT_FROM_SOURCE=OFF`. Please upload the filament binaries for ARM macOS (drag and drop as response to this comment) (as built by cmake during Open3D build), and I'll upload it to the download site with other filament binaries.

File: 3rdparty/librealsense/librealsense.cmake [hunk 2]
```diff
@@ -17,6 +17,9 @@ ExternalProject_Add(
     COMMAND ${GIT_EXECUTABLE} init
     COMMAND ${GIT_EXECUTABLE} apply --ignore-space-change --ignore-whitespace
         ${CMAKE_CURRENT_LIST_DIR}/fix-cudacrt.patch
+    # Patch for macOS ARM64 support for versions < 2.50.0
```
Comment (ssheorey) [inline 3rdparty/librealsense/librealsense.cmake:20]: TODO: Upgrade librealsense to latest so that the patch isn't needed. We can create an issue for this.

File: .github/workflows/macos.yml [hunk 3]
```diff
@@ -116,27 +134,33 @@ jobs:
...
+        os: [macos-12, macos-14]
         python_version: ['3.8', '3.9', '3.10', '3.11']
         is_main:
           - ${{ github.ref == 'refs/heads/main' }}
         exclude:
-          - is_main: false
+          - os: macos-14
             python_version: '3.8'
-          - is_main: false
+          - os: macos-14
```
Comment (ssheorey) [inline .github/workflows/macos.yml:156]: OK to just move all macOS CI (for feature branches) to Python 3.9 for simplicity (no need to have separate options for Intel vs ARM). For main branch, we would need to keep 3.8-3.11 for Intel and 3.9-3.11 for ARM.

**Review by ssheorey — COMMENTED** [review]
Thanks for adding this @sitic Let me know if you need any help, or when it's ready for review.

File: .github/workflows/macos.yml (hunk 3 above)
Comment (sitic) [reply .github/workflows/macos.yml:157]: The setup-python action for macOS arm64 currently doesn't work for Python 3.9 unfortunately, see [setup-python#808](https://github.com/actions/setup-python/issues/808). Pull request [python-versions#259](https://github.com/actions/python-versions/pull/259) will fix this, once it's merged we the `if` statements to exclude python < 3.10 for the arm64 runner.

File: util/ci_utils.sh (hunk 1 above)
Comment (sitic) [reply util/ci_utils.sh]: Here are the arm64 binaries [filament-v1.9.19-macos_arm64.tgz](https://github.com/isl-org/Open3D/files/14736882/filament-v1.9.19-macos_arm64.tgz) from [this CI build](https://github.com/isl-org/Open3D/actions/runs/8408058252). Please upload them to https://github.com/isl-org/open3d_downloads/releases/filament/, I'll update the link.

**Comment by sitic** [comment]
MacOS says the arm64 version of the app is damaged when I try to open it:


`xattr -c Open3D.app` fixes the issue.

I don't understand why this warning instead of the unsigned developer one comes up. The only difference with the `x64` version I see is that the arm64 bundles `libomp.dylib`, while the x64 doesn't.

Code-signing should probably resolve this issue.

File: 3rdparty/librealsense/librealsense.cmake (hunk 2 above)
Comment (sitic) [reply 3rdparty/librealsense/librealsense.cmake:20]: I've opened #6714, however builds fail across all platforms currently due to linking and configuration errors. I'll check whats needed to fix them.

**Comment by sitic** [comment]
@ssheorey should be ready for review, I'm waiting for CI to complete

**Comment by ssheorey** [comment]
Hi @errissa can you take a look at this PR, and also test the built artifacts (wheel, viewer, ...) on both Intel and ARM64 macOS systems?

File: cpp/tests/geometry/TriangleMesh.cpp [hunk 4]
```diff
@@ -1843,33 +1843,121 @@ TEST(TriangleMesh, CreateFromPointCloudPoisson) {
...
+        {44, 50, 43},
+        {32, 31, 50},
+#if defined(__APPLE__) && defined(__arm64__)
+        // Unkown why these two triangles are different on Apple Silicon
+        {44, 45, 50},
+        {45, 32, 50},
+#else
+        {44, 32, 50},
+        {44, 45, 32},
+#endif
```
Comment (ssheorey) [inline cpp/tests/geometry/TriangleMesh.cpp:1928]: Looks like the set of 4 vertices is triangulated in two different but equivalent ways. Numerical differences can cause this. Much more common when you compare CPU vs CUDA results.

File: .github/workflows/macos.yml [hunk 5]
```diff
@@ -47,26 +49,42 @@ jobs:
...
+          if [[ ${{ runner.arch}} == "X64"  ]]; then
+            brew unlink libomp
+            # x64 catalina (10.15) bottle
+            export LIBOMP_BOTTLE_HASH=45a5aa653bd45bd5ff5858580b1a4670c4b5a51ea29d68d45a53f72f56010e05
+          else # ARM64
+            # fix gfortran not found issue
+            ln -s $(which gfortran-13) /usr/local/bin/gfortran
+
+            # default Xcode 15.0.1 linker causes build issues, embree recommends clang <= 14 for arm64
+            sudo xcode-select -switch /Applications/Xcode_14.3.1.app
```
[the remark this answers is not in the document]
Comment (sitic) [reply .github/workflows/macos.yml]: No, it's not. I've moved it up. The default Xcode (15.0.1) for the macos-14 runner uses a new linker (ld-prime) which causes build issues. Newer Xcode versions fix these problems, but I decided to use Xcode 14.3.1 because the embree release mentions possible "EXEC_BAD_INSTRUCTION" runtime exceptions for Xcode >= 15: https://github.com/embree/embree/releases/tag/v4.3.1

I haven't seen these runtime exceptions being triggered. Added all of that as a code comment.

File: cpp/tests/geometry/TriangleMesh.cpp (hunk 4 above)
Comment (sitic) [reply cpp/tests/geometry/TriangleMesh.cpp:1928]: I was thinking along those lines, I've updated the code comment to a clearer version

File: 3rdparty/filament/filament_download.cmake [hunk 6]
```diff
@@ -26,9 +26,19 @@ else()
             string(APPEND lib_dir /x86_64/md)
         endif()
     elseif(APPLE)
-        set(FILAMENT_URL https://github.com/google/filament/releases/download/v1.9.19/filament-v1.9.19-mac.tgz)
-        set(FILAMENT_SHA256 2765d0ce60647fc17d1880c4618cf7d6b5343d8be4dad87978c3917d9c723b4e)
-        string(APPEND lib_dir /x86_64)
+        if (APPLE_AARCH64)
+            ## TODO: Update url
+            set(FILAMENT_URL https://github.com/sitic/filament/releases/download/filament/filament-v1.9.19-macos_arm64.tgz)
+            # set(FILAMENT_URL https://github.com/isl-org/open3d_downloads/releases/download/filament/filament-v1.9.19-macos_arm64.tgz)
```
Comment (ssheorey) [inline 3rdparty/filament/filament_download.cmake:32]: arm64 filament binaries are now uploaded to this URL. OK to update URL.
https://github.com/isl-org/open3d_downloads/releases/download/filament/filament-v1.9.19-macos_arm64.tgz

**Review by ssheorey — COMMENTED** [review]
Tested universal wheels on x86_64. Need testing on arm64 @errissa 
Filament arm64 binaries uploaded to open3d_downloads.

@sitic only request would be to create fused binaries for the viewer app and the devel package. Good to merge after that.

File: docs/getting_started.in.rst [hunk 7]
```diff
@@ -82,10 +82,10 @@ version (``HEAD`` of ``main`` branch):
...
-      - `Python 3.9 <https://storage.googleapis.com/open3d-releases/python-wheels/open3d-@OPEN3D_VERSION_FULL@-cp39-cp39-macosx_11_0_x86_64.whl>`__
-      - `Python 3.10 <https://storage.googleapis.com/open3d-releases/python-wheels/open3d-@OPEN3D_VERSION_FULL@-cp310-cp310-macosx_11_0_x86_64.whl>`__
-      - `Python 3.11 <https://storage.googleapis.com/open3d-releases/python-wheels/open3d-@OPEN3D_VERSION_FULL@-cp311-cp311-macosx_10_15_universal2.whl>`__
+      - `Python 3.8 <https://storage.googleapis.com/open3d-releases/python-wheels/open3d-@OPEN3D_VERSION_FULL@-cp38-cp38-macosx_10_5_x86_64.whl>`__
+      - `Python 3.9 <https://storage.googleapis.com/open3d-releases/python-wheels/open3d-@OPEN3D_VERSION_FULL@-cp39-cp39-macosx_10_5_x86_64.whl>`__
+      - `Python 3.10 <https://storage.googleapis.com/open3d-releases/python-wheels/open3d-@OPEN3D_VERSION_FULL@-cp310-cp310-macosx_10_5_universal2.whl>`__
+      - `Python 3.11 <https://storage.googleapis.com/open3d-releases/python-wheels/open3d-@OPEN3D_VERSION_FULL@-cp311-cp311-macosx_10_5_universal2.whl>`__
```
[the remark this answers is not in the document]
Comment (sitic) [reply docs/getting_started.in.rst]: ups, thanks for catching that

**Comment by sitic** [comment]
I've added a job to merge the x64 and arm64 viewer `.app` bundles. I don't get the "damaged" warning from my last comment anymore, only the normal downloaded app warning.

One remaining difference between the x64 and Apple Silicon builds is WebRTC support, it's currently disabled in the Apple Silicon builds. We should probably fix that.

That would also make it challenging to create universal devel packages because the includes are different. I've tried running the WebRTC workflow to build the arm64 binaries, for the currently pinned WebRTC commit the builds fail for all runners ([CI job](https://github.com/sitic/Open3D/actions/runs/8502466611/job/23286667650)) because some upstream build binary seems to be deleted. For a recent WebRTC commit one of the patches to control CXX11 ABI [fails](https://github.com/sitic/Open3D/actions/runs/8502734107/job/23287296053). I'll take a look if the WebRTC build is easy to fix.

Another issue for creating an universal devel package is that the `INTERFACE_LINK_OPTIONS ` options of the `Open3D::Open3D` target in `Open3DTargets.cmake` are different. The `INTERFACE_LINK_OPTIONS` contains a lot of `\$<LINK_ONLY:\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libz.a>;` type of options, but the exact list of libraries is different between x64 and Apple Silicon: 

<details>

X64 build:

```cmake
set_target_properties(Open3D::Open3D PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_GLIBCXX_USE_CXX11_ABI=0;_GLIBCXX_USE_CXX11_ABI=0;FMT_HEADER_ONLY=0;FMT_USE_WINDOWS_H=0;FMT_STRING_ALIAS=1"
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/open3d/3rdparty;${_IMPORT_PREFIX}/include/open3d/3rdparty;${_IMPORT_PREFIX}/include/open3d/3rdparty;${_IMPORT_PREFIX}/include/open3d/3rdparty"
  INTERFACE_LINK_LIBRARIES "Open3D::3rdparty_eigen3;Open3D::3rdparty_parallelstl"
  INTERFACE_LINK_OPTIONS "\$<\$<STREQUAL:\$<TARGET_PROPERTY:Open3D::Open3D,TYPE>,STATIC_LIBRARY>:\$<LINK_ONLY:\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libz.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libzmq.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersGeneral-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersSources-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersModeling-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersCore-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonExecutionModel-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonDataModel-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonTransforms-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonMath-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonMisc-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonSystem-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonCore-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkkissfft-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkpugixml-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtksys-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libUVAtlas.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libmkl_intel_ilp64.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libmkl_tbb_thread.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libmkl_core.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libtbb_static.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libippiw.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libippicv.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libembree4.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libembree_sse42.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libsimd.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,liblexers.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libsys.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libmath.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libtasking.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libwebrtc.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libwebrtc_extra.a>>>"
)
```

Apple Silicon build:

```cmake
set_target_properties(Open3D::Open3D PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_GLIBCXX_USE_CXX11_ABI=0;_GLIBCXX_USE_CXX11_ABI=0;FMT_HEADER_ONLY=0;FMT_USE_WINDOWS_H=0;FMT_STRING_ALIAS=1"
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/open3d/3rdparty;${_IMPORT_PREFIX}/include/open3d/3rdparty;${_IMPORT_PREFIX}/include/open3d/3rdparty;${_IMPORT_PREFIX}/include/open3d/3rdparty"
  INTERFACE_LINK_LIBRARIES "Open3D::3rdparty_eigen3;Open3D::3rdparty_parallelstl"
  INTERFACE_LINK_OPTIONS "\$<\$<STREQUAL:\$<TARGET_PROPERTY:Open3D::Open3D,TYPE>,STATIC_LIBRARY>:\$<LINK_ONLY:\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libz.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libzmq.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersGeneral-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersSources-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersModeling-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkFiltersCore-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonExecutionModel-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonDataModel-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonTransforms-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonMath-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonMisc-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonSystem-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkCommonCore-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkkissfft-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtkpugixml-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libvtksys-9.1.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libUVAtlas.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libopenblas.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libembree4.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libembree_avx2.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libsimd.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,liblexers.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libsys.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libmath.a>;\$<\$<CXX_COMPILER_ID:GNU>:LINKER:--exclude-libs,libtasking.a>>>"
)
```
</details>

The WebRTC support and the `INTERFACE_LINK_OPTIONS` of `Open3DTargets.cmake` are the only differences otherwise, the `.dylib` libraries would be easy to merge with `lipo -create ARM64/lib/open3d_tf_ops.dylib X64/lib/libOpen3D.dylib -output libOpen3D.dylib`.
```bash
$ diff -qr ARM64 X64                             
Files ARM64/include/open3d/Open3D.h and X64/include/open3d/Open3D.h differ
Files ARM64/lib/cmake/Open3D/Open3DTargets.cmake and X64/lib/cmake/Open3D/Open3DTargets.cmake differ
Files ARM64/lib/libOpen3D.dylib and X64/lib/libOpen3D.dylib differ
Files ARM64/lib/open3d_tf_ops.dylib and X64/lib/open3d_tf_ops.dylib differ
Files ARM64/lib/open3d_torch_ops.dylib and X64/lib/open3d_torch_ops.dylib differ
Only in X64/share/resources: html
```

File: .github/workflows/macos.yml [hunk 8]
```diff
@@ -227,17 +275,95 @@ jobs:
           gsutil cp build/lib/python_package/pip_package/${{ env.PIP_PKG_NAME }} gs://open3d-releases/python-wheels/
           echo "Download pip package at: https://storage.googleapis.com/open3d-releases/python-wheels/${{ env.PIP_PKG_NAME }}"
 
+  fuse-wheel:
```
[the remark this answers is not in the document]
Comment (sitic) [reply .github/workflows/macos.yml:307]: @ssheorey see my comment below.

**Comment by ssheorey** [comment]
Thanks @sitic I think this PR looks very good already. I'm going to go ahead and merge it. Let's work on adding support for WebRTC (remote rendering) for macOS ARM64 in a new PR. Looks like we may need to update the WebRTC version.

**Review by ssheorey — APPROVED** [review]
Tested fused macOS python wheels and fused macOS viewer on Intel macOS.
