### PR TITLE
Fix incomplete VoxelGrid creation from triangles intersecting multiple voxels

### LINKED ISSUE #6324: Strange VoxelGrid result from a TriangleMesh
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When creating a VoxelGrid from a simple TriangleMesh representing a cube, I get a strange result, which is very different from what I would expect and much different from the VoxelGrid created from the sampled PointCloud of that mesh.
The mesh itself is a simple cube constructed from 8 unique vertices.
It seems like the issue described in #6111.

### Steps to reproduce the bug

```python
import open3d
import numpy as np

mesh = open3d.geometry.TriangleMesh()
mesh.vertices = open3d.utility.Vector3dVector(np.array([[ 45.69434738, 268.5824585 ,  22.96587944],
        [ 45.69434738, 268.5824585 ,  25.59055138],
        [ 45.69434738, 270.55096436,  22.96587944],
        [ 45.69434738, 270.55096436,  25.59055138],
        [ 47.66285324, 268.5824585 ,  22.96587944],
        [ 47.66285324, 268.5824585 ,  25.59055138],
        [ 47.66285324, 270.55096436,  22.96587944],
        [ 47.66285324, 270.55096436,  25.59055138]]).reshape((-1, 3)))
mesh.triangles = open3d.utility.Vector3iVector(np.array([1, 5, 3, 3, 5, 7, 0, 2, 4, 4, 2, 6, 6, 2, 7, 7, 2, 3, 2, 0, 3, 3, 0, 1, 0, 4, 1, 1, 4, 5, 4, 6, 5, 5, 6, 7]).reshape((-1, 3)))

voxel_grid = open3d.geometry.VoxelGrid.create_from_triangle_mesh(mesh, voxel_size=0.05)
voxel_grid_from_point_cloud = open3d.geometry.VoxelGrid.create_from_point_cloud(mesh.sample_points_uniformly(100_000), 0.05)
```

### Error message

Mesh itself:
image

Result of VoxelGrid:
image

Result of VoxelFridFromPointCloud:
image

### Expected behavior

I would expect the VoxelGrid from the TriangleMesh to look very much like the mesh itself, the same as the one constructed from the PointCloud looks like.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.9
- Open3D version: 0.17.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): -
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sharon-br**
Set all the relevant voxels, since a triangle can span across multiple ones
Currently, we break after the first voxel in the depth axis for some reason, but a single triangle can be relevant to multiple voxels.

Is there any option to release a version including this PR, since I really want to integrate this into a solution I'm building.

## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6324
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context
The current voxel grid generated is wrong and contains only the first voxel in the depth axis.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [ ] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

Mesh itself I've tested:
image

VoxelGrid before the fix:
image

VoxelGrid after the fix:
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6325)

### CODE REVIEW

**Comment by ssheorey** [comment]
> Is there any option to release a version including this PR, since I really want to integrate this into a solution I'm building.

Hi @sharon-br thanks for the bug fix. We'll get back with reviews shortly. Once the PR is merged, you can use the devel packages from here:

http://www.open3d.org/docs/latest/getting_started.html

(both C++ binaries and Python wheels are available) till the next release is ready.

**Comment by sharon-br** [comment]
@theNded @reyanshsolis Any chance one of you guys can review this, please?

**Comment by reyanshsolis** [comment]
> @theNded @reyanshsolis Any chance one of you guys can review this, please?

Yes, on it... Give me a couple days please.

**Comment by reyanshsolis** [comment]
> @theNded @reyanshsolis Any chance one of you guys can review this, please?

Thanks for your contribution. Will do it by tonight.

File: cpp/open3d/geometry/VoxelGridFactory.cpp [hunk 1]
```diff
@@ -143,7 +143,6 @@ std::shared_ptr<VoxelGrid> VoxelGrid::CreateFromTriangleMeshWithinBounds(
                                 box_center, box_half_size, v0, v1, v2)) {
                         Eigen::Vector3i grid_index(widx, hidx, didx);
                         output->AddVoxel(geometry::Voxel(grid_index));
-                        break;
```
Comment (theNded) [inline cpp/open3d/geometry/VoxelGridFactory.cpp:146]: Add comment here why we should not break (you can simply rephrase your commit message).

**Review by theNded — APPROVED** [review]
LGTM. Please change the PR title to a concise, imperative one, e.g. "Fix incomplete VoxelGrid creation from triangles intersecting multiple voxels."

File: cpp/open3d/geometry/VoxelGridFactory.cpp (hunk 1 above)
Comment (sharon-br) [reply cpp/open3d/geometry/VoxelGridFactory.cpp:146]: Done.

**Comment by sharon-br** [comment]
Done - is there anything else we need in order to merge this?

**Review by reyanshsolis — APPROVED** [review]
LGTM

**Comment by sharon-br** [comment]
@reyanshsolis Your comment commit broke the style check and therefore the test failed, I pushed another commit that fixes that.

**Comment by ssheorey** [comment]
Thanks @sharon-br for the bugfix. Thanks @theNded and @reyanshsolis for reviews!
