### PR TITLE
Unified cloud initializer pipeline for ICP (fixes segfault colored ICP)

### LINKED ISSUE #6935: Segmentation Fault for Colored Point Cloud Registration
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

I have been trying to fit two colored point clouds together using colored icp and it returns a segfault every single time. I know some other issue has brought up a similar issue but for the general icp_registration.

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np

cylinder = o3d.geometry.TriangleMesh.create_cylinder(radius=0.05, height=0.3, resolution=20, split=20)
cylinder.paint_uniform_color([0.5, 0.5, 0.5])
points = cylinder.sample_points_uniformly(3000)

# assign color to the points
points.colors = o3d.utility.Vector3dVector([np.random.rand(3) for i in range(len(points.points))])

# Visualize the pointcloud
# o3d.visualization.draw_geometries([points])

# color the cylinder with the same color as the pointcloud
kdtree = o3d.geometry.KDTreeFlann(cylinder)

# For each point in the point cloud, find the nearest vertex on the mesh
print(len(points.points), len(cylinder.vertices))
for i, point in enumerate(points.points):
    _, idx, _ = kdtree.search_knn_vector_3d(point, 1)  # KNN search for 1 nearest neighbor
    nearest_vertex_index = idx[0]

    # print(nearest_vertex_index, i, len(self.pc_colors), len(self.mesh.vertex_colors))
    
    # Transfer the color from the point cloud to the corresponding mesh vertex
    # print(idx, i)
    cylinder.vertex_colors[nearest_vertex_index] = points.colors[i]

# Visualize the colored mesh
# o3d.visualization.draw_geometries([cylinder])

# sample new points from the cylinder
new_points = cylinder.sample_points_uniformly(2500)
# rotate the cylinder
R = cylinder.get_rotation_matrix_from_xyz((0, 0, np.pi/12))
new_points.points = o3d.utility.Vector3dVector(np.asarray(new_points.points) @ R.T)

# display the new points

voxel_size = 0.001
# downsample the pointclouds
points = points.voxel_down_sample(voxel_size)
new_points = new_points.voxel_down_sample(voxel_size)
new_points.estimate_normals()
o3d.visualization.draw_geometries([points, new_points])

result = o3d.pipelines.registration.registration_icp(
    points, new_points, max_correspondence_distance=1.5*voxel_size, init=np.eye(4),
    estimation_method=o3d.pipelines.registration.TransformationEstimationForColoredICP(),
criteria=o3d.pipelines.registration.ICPConvergenceCriteria(relative_fitness=1e-6,
                                                          relative_rmse=1e-6,
                                                          max_iteration=300))

print(result.transformation)
```

### Error message

Segmentation fault (core dumped)

### Expected behavior

A print of the transformation from one pointcloud to the other (if it has converged)

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: Python 3.10.12
- Open3D version: 0.18.0
- System architecture: x86 
- How did you install Open3D?: pip
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nicolaloi**
## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6935 
-   [x] New feature (non-breaking change which adds functionality). Resolves #6935 
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

The [`RegistrationICP`](https://github.com/isl-org/Open3D/blob/v0.18.0/cpp/open3d/pipelines/registration/Registration.cpp#L108) function can be used to perform point-to-point ICP, point-to-plane ICP, generalized ICP, or colored ICP. Additionally, there are specific functions, [`RegistrationGeneralizedICP`](https://github.com/isl-org/Open3D/blob/v0.18.0/cpp/open3d/pipelines/registration/GeneralizedICP.cpp#L150) and [`RegistrationColoredICP`](https://github.com/isl-org/Open3D/blob/v0.18.0/cpp/open3d/pipelines/registration/ColoredICP.cpp#L214), for computing generalized ICP and colored ICP only, respectively. These functions are simple wrappers around `RegistrationICP`: they initialize the point clouds for the specific ICP algorithm (e.g., computing color gradients for colored ICP) and then call the `RegistrationICP` function with the modified point clouds.

However, this point cloud initialization is skipped if you directly call the `RegistrationICP` function to compute generalized ICP or colored ICP because the initialization is only performed in the wrapper functions. While this is not a significant issue for generalized ICP, it causes a segmentation fault for colored ICP, as the target point cloud must be initialized as an instance of [`PointCloudForColoredICP`](https://github.com/isl-org/Open3D/blob/v0.18.0/cpp/open3d/pipelines/registration/ColoredICP.cpp#L26-L92) to compute the additional `color_gradients_` values.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [x] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [x] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

This PR introduces a unified point cloud initialization pipeline. A new virtual function, `InitializePointCloudsForTransformation`, is added to the [`TransformationEstimation`](https://github.com/isl-org/Open3D/blob/v0.18.0/cpp/open3d/pipelines/registration/TransformationEstimation.h#L42) class. This function is overridden in derived classes to handle the specific initialization required for each specific ICP algorithm, and is being called at the beginning of the `RegistrationICP` function.

This fixes the segmentation fault that occurs when calling `RegistrationICP` for colored ICP, because now the target point cloud will be correctly initialized with the `color_gradient_` values. It also allows `RegistrationICP` to compute generalized ICP with point clouds that don't have pre-computed normals. Previously, this was only possible by calling the `RegistrationGeneralizedICP` wrapper, which exclusively handled the initialization of the point clouds.
 
With this change the point clouds are correctly and consistently initialized across the different ICP algorithms, regardless of whether the user directly calls `RegistrationICP` or a specialized wrapper function like `RegistrationColoredICP`. 

#### Testing
```python
import open3d as o3d
import numpy as np

cylinder = o3d.geometry.TriangleMesh.create_cylinder(radius=0.05, height=0.3, resolution=20, split=20)
source = cylinder.sample_points_uniformly(3000)
source.colors = o3d.utility.Vector3dVector([np.random.rand(3) for i in range(len(source.points))])
target = o3d.geometry.PointCloud(source)
target.transform(np.array([[1, 0, 0, 0.03], [0, 1, 0, 0.01], [0, 0, 1, 0.03], [0, 0, 0, 1]]))
target.estimate_normals()
o3d.visualization.draw_geometries([source, target])

print("Colored ICP using registration_colored_icp")
result_registration_colored_icp = o3d.pipelines.registration.registration_colored_icp(
        source, target, max_correspondence_distance=0.1, init=np.eye(4))
print(result_registration_colored_icp.transformation)
source_copy = o3d.geometry.PointCloud(source)
source_copy.transform(result_registration_colored_icp.transformation)
o3d.visualization.draw_geometries([source_copy, target])

print("\nColored ICP using registration_icp")
result_registration_icp = o3d.pipelines.registration.registration_icp(
        source, target, max_correspondence_distance=0.1, init=np.eye(4),
        estimation_method=o3d.pipelines.registration.TransformationEstimationForColoredICP())
print(result_registration_icp.transformation)
source_copy = o3d.geometry.PointCloud(source)
source_copy.transform(result_registration_icp.transformation)
o3d.visualization.draw_geometries([source_copy, target])
```
##### Before
```
Colored ICP using registration_colored_icp
[[ 1.00000000e+00 -1.11207724e-16  1.83706789e-16  3.00000000e-02]
 [ 1.14820460e-16  1.00000000e+00 -1.51820511e-16  1.00000000e-02]
 [-1.84268345e-16  1.54561401e-16  1.00000000e+00  3.00000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Colored ICP using registration_icp
Segmentation fault (core dumped)
```

##### After
```
Colored ICP using registration_colored_icp
[[ 1.00000000e+00 -2.48679083e-17 -1.71910316e-17  3.00000000e-02]
 [ 7.51766613e-18  1.00000000e+00  3.07426720e-18  1.00000000e-02]
 [ 1.81022819e-17 -4.90281364e-18  1.00000000e+00  3.00000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Colored ICP using registration_icp
[[ 1.00000000e+00 -2.55269579e-17 -1.41811654e-17  3.00000000e-02]
 [ 1.24054495e-17  1.00000000e+00  4.40279123e-18  1.00000000e-02]
 [ 2.22888068e-17 -3.62925246e-18  1.00000000e+00  3.00000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```

### CODE REVIEW

**Comment by nicolaloi** [comment]
CI tests before merging with main: https://github.com/isl-org/Open3D/pull/6942/checks?check_run_id=29583811068,

**Comment by nicolaloi** [comment]
@ssheorey @benjaminum friendly ping if you have time to review this PR.

File: cpp/open3d/pipelines/registration/TransformationEstimation.cpp [hunk 1]
```diff
@@ -89,6 +109,29 @@ Eigen::Matrix4d TransformationEstimationPointToPlane::ComputeTransformation(
...
+TransformationEstimationPointToPlane::InitializePointCloudsForTransformation(
+        const geometry::PointCloud &source,
+        const geometry::PointCloud &target,
+        double max_correspondence_distance) const {
+    if (!target.HasNormals()) {
+        utility::LogError(
+                "PointToPlaneICP requires target pointcloud to have normals.");
+    }
+    std::shared_ptr<const geometry::PointCloud> source_initialized_c(
+            &source, [](const geometry::PointCloud *) {});
```
Comment (benjaminum) [inline cpp/open3d/pipelines/registration/TransformationEstimation.cpp:123]: Thanks for the PR @nicolaloi.  Can you explain why the deleter is empty here?

Comment (nicolaloi) [reply cpp/open3d/pipelines/registration/TransformationEstimation.cpp:123]: @benjaminum In some cases, like for PointToPoint and PointToPlane ICP, no actual modification/initialization of the point clouds is required. However, now there is a consistent interface across different ICP algorithms, so even in these cases the initialization function is being called, which is returning *shared pointers to const point clouds*. Since in these cases the point clouds remain unchanged during the initialization step, creating a costly copy would be unnecessary (eg *pc_initialized = make_shared<PointCloud>(pc_original)*). Instead, I’m creating the shared pointers from the addresses of the original point clouds, effectively creating a const "view" of the originals. The empty deleter ensures that when these shared pointers go out of scope, they don't free the memory owned by the original point clouds.

Comment (benjaminum) [reply cpp/open3d/pipelines/registration/TransformationEstimation.cpp:123]: OK, got it.

**Review by benjaminum — APPROVED** [review]
lgtm
